site_name: Rh-s-PyTool
site_url: https://github.com/skahanium/Rh-s-PyTool-Documentation

repo_url: https://github.com/skahanium/Rh-s-PyTool
repo_name: skahanium/Rh-s-PyTool
edit_uri: ""

nav:
  - Quick Start:
      - 简介: index.md
      - 下载: install.md
  - Methods:
      - Topsis: methods/TOPSIS.md
  - API:
      - cp_lookup: api/cp_lookup.md
      - index_calmeth: api/index_calmeth.md
  - Examples:
      - cp_lookup: examples/cp_lookup.md
      - index_calmeth: examples/index_calmeth.md

theme:
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    - toc.follow

  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      separator: '[\\s\\u200b\\-]'

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-XXXXXXXXXX

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - footnotes
  - abbr

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 Skahanium
