[project]
name = "Rh-s-PyTool"
version = "0.1.3"
description = "Python code instruments that could be used for index comprehensive evaluation."
authors = [
    {name = "skahanium", email = "skahanium@gmail.com"},
]
readme = "README.md"
dependencies = [
    "numpy>=1.22.3",
    "mkdocs-material>=8.2.14",
    "pymdown-extensions>=9.4",
    "markdown>=3.3.7",
    "jinja2>=3.1.2",
    "pygments>=2.12.0",
    "mkdocs>=1.3.0",
    "mkdocs-material-extensions>=1.0.3",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[project.urls]
Github = "https://github.com/skahanium/Rh-s-PyTool"
Documentation = "https://skahanium.github.io/Rh-s-PyTool/"

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
